// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	billingpb "github.com/paysuper/paysuper-proto/go/billingpb"

	mock "github.com/stretchr/testify/mock"
)

// FeedbackRepositoryInterface is an autogenerated mock type for the FeedbackRepositoryInterface type
type FeedbackRepositoryInterface struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: _a0
func (_m *FeedbackRepositoryInterface) GetAll(_a0 context.Context) ([]*billingpb.PageReview, error) {
	ret := _m.Called(_a0)

	var r0 []*billingpb.PageReview
	if rf, ok := ret.Get(0).(func(context.Context) []*billingpb.PageReview); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*billingpb.PageReview)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: _a0, _a1
func (_m *FeedbackRepositoryInterface) Insert(_a0 context.Context, _a1 *billingpb.PageReview) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *billingpb.PageReview) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
