// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Mapper is an autogenerated mock type for the Mapper type
type Mapper struct {
	mock.Mock
}

// MapMgoToObject provides a mock function with given fields: obj
func (_m *Mapper) MapMgoToObject(obj interface{}) (interface{}, error) {
	ret := _m.Called(obj)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(interface{}) interface{}); ok {
		r0 = rf(obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(obj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MapObjectToMgo provides a mock function with given fields: obj
func (_m *Mapper) MapObjectToMgo(obj interface{}) (interface{}, error) {
	ret := _m.Called(obj)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(interface{}) interface{}); ok {
		r0 = rf(obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(obj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
