// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import billingpb "github.com/paysuper/paysuper-proto/go/billingpb"
import context "context"
import mock "github.com/stretchr/testify/mock"

// MerchantPaymentTariffsInterface is an autogenerated mock type for the MerchantPaymentTariffsInterface type
type MerchantPaymentTariffsInterface struct {
	mock.Mock
}

// Find provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4, _a5
func (_m *MerchantPaymentTariffsInterface) Find(_a0 context.Context, _a1 string, _a2 string, _a3 string, _a4 float64, _a5 float64) ([]*billingpb.MerchantTariffRatesPayment, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4, _a5)

	var r0 []*billingpb.MerchantTariffRatesPayment
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, float64, float64) []*billingpb.MerchantTariffRatesPayment); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4, _a5)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*billingpb.MerchantTariffRatesPayment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, float64, float64) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4, _a5)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MultipleInsert provides a mock function with given fields: _a0, _a1
func (_m *MerchantPaymentTariffsInterface) MultipleInsert(_a0 context.Context, _a1 []*billingpb.MerchantTariffRatesPayment) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*billingpb.MerchantTariffRatesPayment) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
