// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import billingpb "github.com/paysuper/paysuper-proto/go/billingpb"
import context "context"
import mock "github.com/stretchr/testify/mock"

// MerchantTariffsSettingsInterface is an autogenerated mock type for the MerchantTariffsSettingsInterface type
type MerchantTariffsSettingsInterface struct {
	mock.Mock
}

// GetByMccCode provides a mock function with given fields: ctx, code
func (_m *MerchantTariffsSettingsInterface) GetByMccCode(ctx context.Context, code string) (*billingpb.MerchantTariffRatesSettings, error) {
	ret := _m.Called(ctx, code)

	var r0 *billingpb.MerchantTariffRatesSettings
	if rf, ok := ret.Get(0).(func(context.Context, string) *billingpb.MerchantTariffRatesSettings); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billingpb.MerchantTariffRatesSettings)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: ctx, merchant
func (_m *MerchantTariffsSettingsInterface) Insert(ctx context.Context, merchant *billingpb.MerchantTariffRatesSettings) error {
	ret := _m.Called(ctx, merchant)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *billingpb.MerchantTariffRatesSettings) error); ok {
		r0 = rf(ctx, merchant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
