// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import billingpb "github.com/paysuper/paysuper-proto/go/billingpb"
import context "context"
import mock "github.com/stretchr/testify/mock"

// MerchantPaymentMethodHistoryRepositoryInterface is an autogenerated mock type for the MerchantPaymentMethodHistoryRepositoryInterface type
type MerchantPaymentMethodHistoryRepositoryInterface struct {
	mock.Mock
}

// Insert provides a mock function with given fields: _a0, _a1
func (_m *MerchantPaymentMethodHistoryRepositoryInterface) Insert(_a0 context.Context, _a1 *billingpb.MerchantPaymentMethodHistory) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *billingpb.MerchantPaymentMethodHistory) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
