// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	billingpb "github.com/paysuper/paysuper-proto/go/billingpb"

	mock "github.com/stretchr/testify/mock"
)

// NotifyRegionRepositoryInterface is an autogenerated mock type for the NotifyRegionRepositoryInterface type
type NotifyRegionRepositoryInterface struct {
	mock.Mock
}

// FindByEmail provides a mock function with given fields: _a0, _a1
func (_m *NotifyRegionRepositoryInterface) FindByEmail(_a0 context.Context, _a1 string) ([]*billingpb.NotifyUserNewRegion, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []*billingpb.NotifyUserNewRegion
	if rf, ok := ret.Get(0).(func(context.Context, string) []*billingpb.NotifyUserNewRegion); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*billingpb.NotifyUserNewRegion)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: _a0, _a1
func (_m *NotifyRegionRepositoryInterface) Insert(_a0 context.Context, _a1 *billingpb.NotifyUserNewRegion) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *billingpb.NotifyUserNewRegion) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
