// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	billingpb "github.com/paysuper/paysuper-proto/go/billingpb"

	mock "github.com/stretchr/testify/mock"

	options "go.mongodb.org/mongo-driver/mongo/options"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// OrderRepositoryInterface is an autogenerated mock type for the OrderRepositoryInterface type
type OrderRepositoryInterface struct {
	mock.Mock
}

// GetById provides a mock function with given fields: _a0, _a1
func (_m *OrderRepositoryInterface) GetById(_a0 context.Context, _a1 string) (*billingpb.Order, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *billingpb.Order
	if rf, ok := ret.Get(0).(func(context.Context, string) *billingpb.Order); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billingpb.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByRefundReceiptNumber provides a mock function with given fields: _a0, _a1
func (_m *OrderRepositoryInterface) GetByRefundReceiptNumber(_a0 context.Context, _a1 string) (*billingpb.Order, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *billingpb.Order
	if rf, ok := ret.Get(0).(func(context.Context, string) *billingpb.Order); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billingpb.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUuid provides a mock function with given fields: _a0, _a1
func (_m *OrderRepositoryInterface) GetByUuid(_a0 context.Context, _a1 string) (*billingpb.Order, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *billingpb.Order
	if rf, ok := ret.Get(0).(func(context.Context, string) *billingpb.Order); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billingpb.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUuidAndMerchantId provides a mock function with given fields: ctx, uuid, merchantId
func (_m *OrderRepositoryInterface) GetByUuidAndMerchantId(ctx context.Context, uuid string, merchantId string) (*billingpb.Order, error) {
	ret := _m.Called(ctx, uuid, merchantId)

	var r0 *billingpb.Order
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *billingpb.Order); ok {
		r0 = rf(ctx, uuid, merchantId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billingpb.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, uuid, merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFirstPaymentForMerchant provides a mock function with given fields: ctx, merchantId
func (_m *OrderRepositoryInterface) GetFirstPaymentForMerchant(ctx context.Context, merchantId string) (*billingpb.Order, error) {
	ret := _m.Called(ctx, merchantId)

	var r0 *billingpb.Order
	if rf, ok := ret.Get(0).(func(context.Context, string) *billingpb.Order); ok {
		r0 = rf(ctx, merchantId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billingpb.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetManyBy provides a mock function with given fields: ctx, filter, opts
func (_m *OrderRepositoryInterface) GetManyBy(ctx context.Context, filter primitive.M, opts ...*options.FindOptions) ([]*billingpb.Order, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, filter)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []*billingpb.Order
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, ...*options.FindOptions) []*billingpb.Order); ok {
		r0 = rf(ctx, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*billingpb.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, primitive.M, ...*options.FindOptions) error); ok {
		r1 = rf(ctx, filter, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOneBy provides a mock function with given fields: ctx, filter, opts
func (_m *OrderRepositoryInterface) GetOneBy(ctx context.Context, filter primitive.M, opts ...*options.FindOneOptions) (*billingpb.Order, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, filter)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *billingpb.Order
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, ...*options.FindOneOptions) *billingpb.Order); ok {
		r0 = rf(ctx, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billingpb.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, primitive.M, ...*options.FindOneOptions) error); ok {
		r1 = rf(ctx, filter, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncludeOrdersToRoyaltyReport provides a mock function with given fields: ctx, royaltyReportId, orderIds
func (_m *OrderRepositoryInterface) IncludeOrdersToRoyaltyReport(ctx context.Context, royaltyReportId string, orderIds []primitive.ObjectID) error {
	ret := _m.Called(ctx, royaltyReportId, orderIds)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []primitive.ObjectID) error); ok {
		r0 = rf(ctx, royaltyReportId, orderIds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Insert provides a mock function with given fields: _a0, _a1
func (_m *OrderRepositoryInterface) Insert(_a0 context.Context, _a1 *billingpb.Order) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *billingpb.Order) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *OrderRepositoryInterface) Update(_a0 context.Context, _a1 *billingpb.Order) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *billingpb.Order) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateOrderView provides a mock function with given fields: _a0, _a1
func (_m *OrderRepositoryInterface) UpdateOrderView(_a0 context.Context, _a1 []string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
