// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PaylinkVisitRepositoryInterface is an autogenerated mock type for the PaylinkVisitRepositoryInterface type
type PaylinkVisitRepositoryInterface struct {
	mock.Mock
}

// CountPaylinkVisits provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *PaylinkVisitRepositoryInterface) CountPaylinkVisits(_a0 context.Context, _a1 string, _a2 int64, _a3 int64) (int64, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) int64); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrVisits provides a mock function with given fields: ctx, id
func (_m *PaylinkVisitRepositoryInterface) IncrVisits(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
