// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import billingpb "github.com/paysuper/paysuper-proto/go/billingpb"
import context "context"
import mock "github.com/stretchr/testify/mock"

// PaylinkRepositoryInterface is an autogenerated mock type for the PaylinkRepositoryInterface type
type PaylinkRepositoryInterface struct {
	mock.Mock
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *PaylinkRepositoryInterface) Delete(_a0 context.Context, _a1 *billingpb.Paylink) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *billingpb.Paylink) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *PaylinkRepositoryInterface) Find(_a0 context.Context, _a1 string, _a2 string, _a3 int64, _a4 int64) ([]*billingpb.Paylink, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	var r0 []*billingpb.Paylink
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, int64) []*billingpb.Paylink); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*billingpb.Paylink)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64, int64) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindCount provides a mock function with given fields: _a0, _a1, _a2
func (_m *PaylinkRepositoryInterface) FindCount(_a0 context.Context, _a1 string, _a2 string) (int64, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: _a0, _a1
func (_m *PaylinkRepositoryInterface) GetById(_a0 context.Context, _a1 string) (*billingpb.Paylink, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *billingpb.Paylink
	if rf, ok := ret.Get(0).(func(context.Context, string) *billingpb.Paylink); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billingpb.Paylink)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIdAndMerchant provides a mock function with given fields: _a0, _a1, _a2
func (_m *PaylinkRepositoryInterface) GetByIdAndMerchant(_a0 context.Context, _a1 string, _a2 string) (*billingpb.Paylink, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *billingpb.Paylink
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *billingpb.Paylink); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billingpb.Paylink)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: _a0, _a1
func (_m *PaylinkRepositoryInterface) Insert(_a0 context.Context, _a1 *billingpb.Paylink) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *billingpb.Paylink) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *PaylinkRepositoryInterface) Update(_a0 context.Context, _a1 *billingpb.Paylink) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *billingpb.Paylink) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTotalStat provides a mock function with given fields: _a0, _a1
func (_m *PaylinkRepositoryInterface) UpdateTotalStat(_a0 context.Context, _a1 *billingpb.Paylink) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *billingpb.Paylink) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
