// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import payment_system "github.com/paysuper/paysuper-billing-server/internal/payment_system"

// PaymentSystemManagerInterface is an autogenerated mock type for the PaymentSystemManagerInterface type
type PaymentSystemManagerInterface struct {
	mock.Mock
}

// GetGateway provides a mock function with given fields: name
func (_m *PaymentSystemManagerInterface) GetGateway(name string) (payment_system.PaymentSystemInterface, error) {
	ret := _m.Called(name)

	var r0 payment_system.PaymentSystemInterface
	if rf, ok := ret.Get(0).(func(string) payment_system.PaymentSystemInterface); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(payment_system.PaymentSystemInterface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
